// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izguihfmrfvwmjiwcysy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Z3VpaGZtcmZ2d21qaXdjeXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzYxODgsImV4cCI6MjA2NTc1MjE4OH0.sA-R7BHOqoOke-pnk6PZmwZ5-LYySbfrGkeMqmoozyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);